### ISSUE TITLE
connection errors with "127.0.0.1:80"

### ISSUE THREAD

**Issue by BakasuraRCE** [Kylart/KawAnime#24]
I'm having many problems with server "127.0.0.1:80"

**Log:**

> KawAnime is at http://localhost:37513
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
[INIT] Local Files
[INIT] Watch List
[Local]: Sending files.
[WatchList] Gathered lists from local.
[Mal-Scraper] (Seasons): Now having winter 2018.
[Mal-Scraper] (News): Finished gathering the news.
[Nyaa] (Releases): Sending Latest releases.
[7:26:08 PM]: Error while checking update. connect ECONNREFUSED 127.0.0.1:80
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
[7:27:08 PM]: Error while checking update. connect ECONNREFUSED 127.0.0.1:80
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
[7:28:08 PM]: Error while checking update. connect ECONNREFUSED 127.0.0.1:80
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
[12:29:08 AM]: Error while checking update. connect ECONNREFUSED 127.0.0.1:80
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
[12:30:08 AM]: Error while checking update. connect ECONNREFUSED 127.0.0.1:80
[MalScraper] (Releases): An error occurred...
Error: Request failed with status code 404
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
[Nyaa] (Releases): Sending Latest releases.
[12:31:08 AM]: Error while checking update. connect ECONNREFUSED 127.0.0.1:80
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3
[12:32:09 AM]: Error while checking update. connect ECONNREFUSED 127.0.0.1:80
Checking for update
Error: Error: ENOENT: no such file or directory, open '/opt/KawAnime/resources/app-update.yml'
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:334:27
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:368:11)
    at Lazy.AppUpdater.configOnDisk.Lazy [as creator] (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:98:43)
    at Lazy.get value [as value] (/opt/KawAnime/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:245:33
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:326:11)
    at /opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:228:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:280:11)
    at AppImageUpdater.checkForUpdates (/opt/KawAnime/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:177:35)
    at module.exports (/opt/KawAnime/resources/app.asar/server/updater.js:28:15)
    at setup (/opt/KawAnime/resources/app.asar/server/index.js:319:37)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:64:40)
    at Object.<anonymous> (/opt/KawAnime/resources/app.asar/main.js:294:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:171:8)
    at Object.<anonymous> (/opt/KawAnime/resources/electron.asar/browser/init.js:173:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:167:16)
    at bootstrap_node.js:589:3

**Comment by Kylart** [comment]
That is totally normal, auto-update cannot work if it's not in a distributable version.

Apparently, here you tried to launch KawAnime via a `npm run start` command. Tbh, I cannot do much about that, I know it is a bit annoying but this particular log means no damage.

**Comment by BakasuraRCE** [comment]
i just installed from here: https://aur.archlinux.org/packages/kawanime/

**Comment by Kylart** [comment]
Oh, the problem is still the same but I'm not really familiar with ArchLinux tbh. I guess the person that made this made it in a way that it launches `npm start` to run the app which make it impossible for the auto updater to update.

Can you try doing the following? If not, I can try it by tomorrow.

```bash
cd test/directory

git clone https://github.com/kylart/kawanime && cd kawanime

npm install && npm run build && npm run dist:linux  # That might take a bit of time

cd dist

chmod +x KawAnime-0.2.3-x86_64.AppImage

./KawAnime-0.2.3-x86_64.AppImage
```

**Comment by BakasuraRCE** [comment]
I'm getting this errors when try build:

> KawAnime@0.2.3 dist:linux /home/user/temp/kawanime
> build --linux deb AppImage

  • electron-builder version=19.52.1
  • loaded configuration file=package.json ("build" field)
Error: At least electron-updater 2.18.2 is required by current electron-builder version. Please set electron-updater version to "^2.18.2"
    at checkMetadata (/home/user/temp/kawanime/node_modules/electron-builder-lib/src/util/packageMetadata.ts:77:11)
    at /home/user/temp/kawanime/node_modules/electron-builder-lib/src/packager.ts:259:5
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Packager.build (/home/user/temp/kawanime/node_modules/electron-builder-lib/out/packager.js:319:11)
    at /home/user/temp/kawanime/node_modules/electron-builder/src/builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (/home/user/temp/kawanime/node_modules/electron-builder/out/builder.js:61:21)
    at build (/home/user/temp/kawanime/node_modules/electron-builder/src/builder.ts:280:10)
    at then (/home/user/temp/kawanime/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/home/user/temp/kawanime/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/home/user/temp/kawanime/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/home/user/temp/kawanime/node_modules/yargs/yargs.js:1023:28)
    at Object.get [as argv] (/home/user/temp/kawanime/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/home/user/temp/kawanime/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! KawAnime@0.2.3 dist:linux: `build --linux deb AppImage`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the KawAnime@0.2.3 dist:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-01-06T06_25_49_583Z-debug.log

**Comment by Kylart** [comment]
There we go! Yet that won't appear on that archLinux package as long as I don't release 0.2.4 I guess?
