### ISSUE TITLE
PuyaSubs! Can't get

### ISSUE THREAD

**Issue by BakasuraRCE** [Kylart/KawAnime#26]
Can't get list of anime from "PuyaSubs!" in the main page, besides I can not go back to the main page to choose another fansub, it stays in a loading and error loop

Log:

[1/6/2018] 1:55:20 AM - ERROR > [Nyaa (Releases)]: An error occurred. 
Error: [Mal-Scraper]: Invalid name.
    at Promise (/tmp/.mount_KawAnixP06Li/app/resources/app.asar/node_modules/mal-scraper/src/info.js:152:14)
    at Promise (<anonymous>)
    at Object.getInfoFromName (/tmp/.mount_KawAnixP06Li/app/resources/app.asar/node_modules/mal-scraper/src/info.js:150:10)
    at makeSearch (/tmp/.mount_KawAnixP06Li/app/resources/app.asar/server/nyaa/getLatest.js:18:16)
    at si.search.then (/tmp/.mount_KawAnixP06Li/app/resources/app.asar/server/nyaa/getLatest.js:46:7)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by Kylart** [comment]
Ahhh, it seems PuyaSubs do not release anime in 480p quality. (I guess that was the quality you chose).

Go to settings > preferred quality > choose 720p or 1080p > Save > Restart the app

**Comment by BakasuraRCE** [comment]
happens when i do click from here:

![image](https://user-images.githubusercontent.com/26231582/34637527-b1fe0a2e-f286-11e7-92f7-51c7d022161a.png)

My preferred config is Erai-raws at 1080p

**Comment by Kylart** [comment]
Thank you for pointing this out! 👍
