### ISSUE TITLE
Error 429 MyAnimeList

### ISSUE THREAD

**Issue by BakasuraRCE** [Kylart/KawAnime#27]
I'm getting a lot of errors 429 on the part of the myanimelist module, apparently rejecting my requests to the server for it's tons in a short time.

Well, I do not know how this can be solved. because it is not a direct error of the program.

Log:

[1/6/2018] 2:28:33 AM - ERROR > [Nyaa (Releases)]: An error occurred. 
Error: Request failed with status code 429
    at createError (/tmp/.mount_KawAnihZDtNJ/app/resources/app.asar/node_modules/mal-scraper/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/tmp/.mount_KawAnihZDtNJ/app/resources/app.asar/node_modules/mal-scraper/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/tmp/.mount_KawAnihZDtNJ/app/resources/app.asar/node_modules/mal-scraper/node_modules/axios/lib/adapters/http.js:192:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by Kylart** [comment]
Yea this error does not come from the app and I cannot do much about it. I'm fighting against this since the beginning of KawAnime actually 😄
