### ISSUE TITLE
Can't get list of anime

### ISSUE THREAD

**Issue by JuanSeabra** [Kylart/KawAnime#35]
I can't get the anime list in the main page with any fansub or quality selected, it stays in a loading and error loop

Log:
```
[INIT] Local Files
[INIT] Watch List
[11/04/2018] 12:06:12 - INFO  > [Local]: Sending files. 
[11/04/2018] 12:06:12 - INFO  > [WatchList]: Gathered lists from local. 
[INIT] Local Files
[INIT] Watch List
[11/04/2018] 12:06:19 - INFO  > [Mal-Scraper (News)]: Finished gathering the news. 
[11/04/2018] 12:06:21 - ERROR > [Nyaa (Releases)]: An error occurred. 
Error: Request failed with status code 429
    at createError (/tmp/.mount_KawAniz3ZHoi/app/resources/app.asar/node_modules/mal-scraper/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/tmp/.mount_KawAniz3ZHoi/app/resources/app.asar/node_modules/mal-scraper/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/tmp/.mount_KawAniz3ZHoi/app/resources/app.asar/node_modules/mal-scraper/node_modules/axios/lib/adapters/http.js:192:11)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1045:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[11/04/2018] 12:06:23 - INFO  > [Mal-Scraper (Seasons)]: Now having spring 2018. 

```

**Comment by Kylart** [comment]
Duplicate #27 

I have a plan to fight this but I cannot implement it right away atm.
