### ISSUE TITLE
libstdc++.so.6: version `GLIBCXX_3.4.26' not found  in 0.4.2-x86_64.AppImage on debian buster

### ISSUE THREAD

**Issue by githuber0815** [Kylart/KawAnime#73]
Hi, 

i tried to run the AppImage on Debian buster and got the following Stacktrace.
```sh
$ ./KawAnime-0.4.2-x86_64.AppImage 
781 775
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.FOLPs6)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_KawAniPHPCae/resources/app.asar/node_modules/anitomy-js/index.js:3:15)
    at Object.<anonymous> (/tmp/.mount_KawAniPHPCae/resources/app.asar/node_modules/anitomy-js/index.js:75:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_KawAniPHPCae/resources/app.asar/background.js:25:18659)
    at n (/tmp/.mount_KawAniPHPCae/resources/app.asar/background.js:1:265)
    at Object.<anonymous> (/tmp/.mount_KawAniPHPCae/resources/app.asar/background.js:1:25268)
    at n (/tmp/.mount_KawAniPHPCae/resources/app.asar/background.js:1:265)
    at Module.<anonymous> (/tmp/.mount_KawAniPHPCae/resources/app.asar/background.js:236:1080288)
```

The 0.4.1-x86_64.AppImage works without this issue. 
I guess, you updated your Build Env. Compiler.

Maybe it can be configured  it to make it downward compatible with older glibc versions?

**Comment by githuber0815** [comment]
Building the dev branch (on commit 68fc6608163c9359d509d2f7daf6341f1c601baa) 
locally and generating the AppImage worked. (although the optinal dependencies dont seem quite so optional, or i missed a switch for def. them as such)  
Anyway,  Version 0.4.2 looks very nice.
 
I still hope you will look into this issue for a future version.

Bye for now :wave:

**Comment by Kylart** [comment]
Right so if you used the dev branch, means you are on what will probably be the next version so `0.5.0` I guess. From this version, the app is using libtorrent and mpv as its main torrent client and video player. Having libtorrent installed on your computer is optional (if not installed, it will install 1.2 locally) and mpv is optional in the sense that if you don't install it, you'll simply be unable to play videos inside the app and will have to use an external player.

From the next version, what you did will be the only way to `install` the app for linux systems so I'm glad it worked 😄 

Enjoy!
