### ISSUE TITLE
appimage 4.2 not working.

### ISSUE THREAD

**Issue by Hdet** [Kylart/KawAnime#77]
Im running linux mint 19.3 .

The previous version 4.1 appimage is running fine on 19.3.
The latest appimage version 4.2  is not working at all. by making it executable en running it does not start at all and no error messages.

hope you can help.

**Comment by ipmanlk** [comment]
Error log,
`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /tmp/.org.chromium.Chromium.Ealcli)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_KawAniTzAV1n/resources/app.asar/node_modules/anitomy-js/index.js:3:15)
    at Object.<anonymous> (/tmp/.mount_KawAniTzAV1n/resources/app.asar/node_modules/anitomy-js/index.js:75:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_KawAniTzAV1n/resources/app.asar/background.js:25:18659)
    at n (/tmp/.mount_KawAniTzAV1n/resources/app.asar/background.js:1:265)
    at Object.<anonymous> (/tmp/.mount_KawAniTzAV1n/resources/app.asar/background.js:1:25268)
    at n (/tmp/.mount_KawAniTzAV1n/resources/app.asar/background.js:1:265)
    at Module.<anonymous> (/tmp/.mount_KawAniTzAV1n/resources/app.asar/background.js:236:1080288)
`

**Comment by Kylart** [comment]
So this seems related to #72 and #73.

You should try building the AppImage from the source code. Just clone the `master` branch and you should be good to go1

**Comment by ipmanlk** [comment]
> So this seems related to #72 and #73.
> 
> You should try building the AppImage from the source code. Just clone the `master` branch and you should be good to go1

building from source appears to be working. I suggest closing this issue.
